### ISSUE TITLE
Headless Background Task can not be executed

### ISSUE THREAD

**Issue by lakemperp** [transistorsoft/flutter_background_fetch#12] opened 2019-02-25 11:51 UTC
Hi,
if the barcode scan library (barcode_scan: ^0.0.8) is used, 
the following exception occurs after the background task is triggered (adb shell cmd jobscheduler run -f <appID> 999)

java.lang.RuntimeException: java.lang.IllegalStateException: registrar.activity() must not be null
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)                                                             
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:108)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7425)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
02-25 11:32:42.472 11461 11461 E AndroidRuntime: Caused by: java.lang.IllegalStateException: registrar.activity() must not be null
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt:19)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.apptreesoftware.barcodescan.BarcodeScanPlugin.registerWith(Unknown Source:2)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:22)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.example.xyz.Application.registerWith(Application.java:17)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(HeadlessTask.java:133)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.<init>(HeadlessTask.java:47)                                                             
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(HeadlessJobService.java:38)                                             
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.job.JobService$1.onStartJob(JobService.j
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java)

The Task will not be excecuted. 
Thanks for your help.

**Comment by christocracy** [comment] 2019-02-25 11:55
This is basically a duplicate of #11.

All plugin developers need to guard themselves against the case where an App can launch Headless, where `registrar.activity() == null`.

**Closed by christocracy** 2019-02-25 11:55 UTC
