### ISSUE TITLE
[BUG] After the app terminated, the background task is not running and result in crash.

### ISSUE THREAD

**Issue by yamachaso** [transistorsoft/flutter_background_fetch#203] opened 2021-03-22 07:26 UTC
* Plugin version: **background_fetch: ^0.7.1**
* Platform: **Android**
* OS version: **9**
* Device: **OPPO** / **OPPO Reno A**
* Flutter info:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!
```

* Plugin config

**To Reproduce**
1. run the example on https://pub.dev/packages/background_fetch/example on my physical device
2. terminated the app by gesturing as shown in the image

<img src="https://user-images.githubusercontent.com/55785032/111952100-efe9e280-8b27-11eb-94b2-d2f5ac84f311.jpg" width="200">

3. simulate a background-fetch event
```
$ adb shell cmd jobscheduler run -f <your.application.id> 999
```
4. the background task doesn't run

**Debug logs**
- Android: `$ adb logcat`
```
$ adb logcat *:S flutter:V, TSBackgroundFetch:V
--------- beginning of crash
--------- beginning of system
--------- beginning of main
03-22 15:45:13.793 24559 24559 D TSBackgroundFetch: - configure
03-22 15:45:13.793 24559 24559 D TSBackgroundFetch: - start
03-22 15:45:13.793 24559 24559 D TSBackgroundFetch: - registerTask: flutter_background_fetch
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch: {
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "taskId": "flutter_background_fetch",
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "isFetchTask": true,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "minimumFetchInterval": 15,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "stopOnTerminate": false,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "requiredNetworkType": 0,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "requiresCharging": false,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "requiresDeviceIdle": false,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "requiresStorageNotLow": false,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "startOnBoot": true,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "forceAlarmManager": false,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "periodic": true,
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch:   "delay": -1
03-22 15:45:13.798 24559 24559 D TSBackgroundFetch: }
03-22 15:45:13.821 24559 24607 I flutter : [BackgroundFetch] configure success: 2
03-22 15:45:13.827 24559 24559 D TSBackgroundFetch: - registerTask: com.transistorsoft.customtask
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch: {
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "taskId": "com.transistorsoft.customtask",
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "isFetchTask": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "minimumFetchInterval": 15,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "stopOnTerminate": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "requiredNetworkType": 0,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "requiresCharging": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "requiresDeviceIdle": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "requiresStorageNotLow": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "startOnBoot": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "forceAlarmManager": true,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "periodic": false,
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch:   "delay": 10000
03-22 15:45:13.828 24559 24559 D TSBackgroundFetch: }
03-22 15:45:13.878 24559 24559 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-22 15:45:13.884 24559 24607 I flutter : [BackgroundFetch] Event received: flutter_background_fetch
03-22 15:45:13.887 24559 24559 D TSBackgroundFetch: - finish: flutter_background_fetch
03-22 15:45:13.887 24559 24559 D TSBackgroundFetch: - jobFinished
03-22 15:45:23.859 24559 24559 D TSBackgroundFetch: - Background Fetch event received: com.transistorsoft.customtask
03-22 15:45:23.863 24559 24607 I flutter : [BackgroundFetch] Event received: com.transistorsoft.customtask
03-22 15:45:23.865 24559 24559 D TSBackgroundFetch: - finish: com.transistorsoft.customtask
03-22 15:45:23.868 24559 24559 D TSBackgroundFetch: - FetchAlarmReceiver finish
03-22 15:46:09.686 24844 24844 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-22 15:46:09.698 24844 24844 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
03-22 15:46:40.025 24870 24870 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-22 15:46:40.038 24870 24870 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
03-22 15:47:40.321 24987 24987 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-22 15:47:40.330 24987 24987 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
03-22 15:49:40.621 25551 25551 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-22 15:49:40.634 25551 25551 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
03-22 15:55:47.169 25665 25665 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-22 15:55:47.181 25665 25665 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
03-22 16:03:47.474 26984 26984 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-22 16:03:47.485 26984 26984 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
```

**Additional context**
```
D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
```
The above two lines were only repeated in spite of the fact that I executed a background-fetch event simulation ONCE, not calling BackgroundFetch.finish method. 
And I simulated a background-fetch event several times, I got this pop-up display on the smartphone screen.
<img src="https://user-images.githubusercontent.com/55785032/111953878-959e5100-8b2a-11eb-888c-13e5a14a1aba.jpg" width="200">
This says ''background_fetch_test failed to start several times. Do you want to clear the history and restore ?''

Could you tell me why this phenomenon happened and how to fix?

**Comment by christocracy** [comment] 2021-03-22 07:58
Remove the filters to logcat.  You're filtering out the stacktrace.

**Comment by yamachaso** [comment] 2021-03-22 08:26
Thank you for your reply. I execute "$ adb logcat" without filtering.
The result was too long to show here so I published it on Gist.

https://gist.github.com/yamachaso/563ecb4bfd9fe65e952268953b345d65

You can see the output of the lines I mentioned above on lines 26, 27, 115, and 116.

26: 03-22 17:09:04.612 31766 31766 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
27: 03-22 17:09:04.623 31766 31766 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]

115: 03-22 17:09:34.868 31793 31793 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
116: 03-22 17:09:34.879 31793 31793 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]

**Comment by christocracy** [comment] 2021-03-22 10:06
What you're interested in is the stacktrace:

```

03-22 17:09:34.882 31793 31793 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.g.b.b' on a null object reference
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at io.flutter.embedding.engine.g.c.d(Unknown Source:2)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(Unknown Source:20)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(Unknown Source:4)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(Unknown Source:0)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:227)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7275)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
03-22 17:09:34.882 31793 31793 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
03-22 17:09:34.896 31793 31793 I Process : Sending signal. PID: 31793 SIG: 9
```

**Comment by yamachaso** [comment] 2021-03-22 12:13
I did this way and the app worked well. Thanks a ton!!
https://github.com/transistorsoft/flutter_background_fetch/issues/160#issuecomment-717206628

But, I'm still nervous about this below.

【AndroidManifest.xml】
```
<application
    android:name="io.flutter.app.FlutterApplication"
    ...
    <activity
        android:name=".MainActivity"
        ...
```
There is "android:name" tag not only in <application> but also in <activity>. Is it OK?

**Comment by christocracy** [comment] 2021-03-23 15:24
>I did this way and the app worked well. Thanks a ton!!

What did your `<application android:name` look like *before*?

> Is it OK?

Yes.

**Comment by christocracy** [comment] 2021-03-23 15:28
When I generate a new app with `flutter create foo`, `AndroidManifest.xml` looks like this and everything works fine (after adding modifying only `tools:replace="android:label"`:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.foo3">
   <application
        android:label="foo3"
        tools:replace="android:label"
        android:icon="@mipmap/ic_launcher">
```

**Comment by yamachaso** [comment] 2021-03-24 09:59
> What did your `<application android:name` look like _before_?

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.foo">
   <application
        android:label="foo"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            ...

```
I also generate a new app with `flutter create foo` and I got this `AndroidManifest.xml` above.
By default, `android:name` doesn't exist inside application tag, only exists inside activity tag.

**Comment by TheLastGimbus** [comment] 2021-03-28 19:15
Hello there! I have the same problem!

I made a separate empty app to debug this, and when I launch it, I get the same error as friend above :confused:

<details><summary>Error logs</summary>
<p>

```
E/flutter (31376): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.
E/flutter (31376): Receiver: null
E/flutter (31376): Tried calling: toRawHandle()
E/flutter (31376): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (31376): #1      BackgroundFetch.registerHeadlessTask (package:background_fetch/background_fetch.dart:606:51)
E/flutter (31376): #2      main (package:dupa12/main.dart:6:19)
E/flutter (31376): #3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
E/flutter (31376): #4      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (31376): #5      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (31376): #6      _runZoned (dart:async/zone.dart:1788:10)
E/flutter (31376): #7      runZonedGuarded (dart:async/zone.dart:1776:12)
E/flutter (31376): #8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
E/flutter (31376): #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (31376): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
D/TSBackgroundFetch(31376): - configure
D/TSBackgroundFetch(31376): - start
D/TSBackgroundFetch(31376): - registerTask: flutter_background_fetch
D/TSBackgroundFetch(31376): {
D/TSBackgroundFetch(31376):   "taskId": "flutter_background_fetch",
D/TSBackgroundFetch(31376):   "isFetchTask": true,
D/TSBackgroundFetch(31376):   "minimumFetchInterval": 15,
D/TSBackgroundFetch(31376):   "stopOnTerminate": false,
D/TSBackgroundFetch(31376):   "requiredNetworkType": 0,
D/TSBackgroundFetch(31376):   "requiresBatteryNotLow": false,
D/TSBackgroundFetch(31376):   "requiresCharging": false,
D/TSBackgroundFetch(31376):   "requiresDeviceIdle": false,
D/TSBackgroundFetch(31376):   "requiresStorageNotLow": false,
D/TSBackgroundFetch(31376):   "startOnBoot": true,
D/TSBackgroundFetch(31376):   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
D/TSBackgroundFetch(31376):   "forceAlarmManager": false,
D/TSBackgroundFetch(31376):   "periodic": true,
D/TSBackgroundFetch(31376):   "delay": -1
D/TSBackgroundFetch(31376): }
D/TSBackgroundFetch(31376): - Background Fetch event received: flutter_background_fetch
```

</p>
</details>

<details><summary>Added mavein in android/build.gradle</summary>
<p>

```gradle
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}
```

</p>
</details>

<details><summary>Added Application.kt in same folder as MainActivity.kt</summary>
<p>

```kotlin
package com.example.dupa12

import io.flutter.app.FlutterApplication

class Application : FlutterApplication() {
    override fun onCreate() {
        super.onCreate()
    }
}

```

</p>
</details>

<details><summary>Added tools:replace and android:name in manifest</summary>
<p>

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.dupa12">
   <application
        <!-- Also tried ".Application", but didn't help anyhow either -->
        android:name="io.flutter.app.FlutterApplication"
        android:label="dupa12"
        android:icon="@mipmap/ic_launcher"
        tools:replace="android:label">
```

</p>
</details>

<details><summary>And here is my whole main.dart</summary>
<p>

```dart
import 'package:background_fetch/background_fetch.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
  BackgroundFetch.registerHeadlessTask(
    (HeadlessTask h) {
      print("YOOOO THIS WORKING HEADLESSS! ${h.taskId}");
      BackgroundFetch.finish(h.taskId);
    },
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    BackgroundFetch.configure(
      BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
      ),
      (String taskId) {
        print("Yeah this working in background! $taskId");
        BackgroundFetch.finish(taskId);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('dupa')),
      body: Center(child: Text('nothing')),
    );
  }
}

```

</p>
</details>


<details><summary>Oh, and flutter doctor of course</summary>
<p>

```
mateusz@botbox:~/dev/projects/flutter/dupa12$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)  // This is weird, as I have it fully instaled and working, but whatever
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

</p>
</details>

**Comment by christocracy** [comment] 2021-03-28 19:49
@TheLastGimbus You've not stated what version of the plugin you're using.

**Comment by TheLastGimbus** [comment] 2021-03-28 19:54
Oops, sorry, last thing I forgot, latest one: `background_fetch: ^0.7.1`

**Comment by christocracy** [comment] 2021-03-28 19:56
Don't you want to be using version `1.0.0-nullsafety.1` since your `flutter doctor` says `Channel stable, 2.0.0`?

**Comment by christocracy** [comment] 2021-03-28 19:57
https://pub.dev/packages/background_fetch/versions/1.0.0-nullsafety.1

**Comment by TheLastGimbus** [comment] 2021-03-28 20:01
Maybe, but it looks like a pre-release so I didn't touch it - does it resolve our problem?

<sub>Also, my main app is not migrated to null safety at all, so...</sub>

**Comment by christocracy** [comment] 2021-03-28 20:04
If your app is not configured for *nullsaftey*, then you don't want to use the *nullsafety* version.

**Comment by christocracy** [comment] 2021-03-28 20:06
I suggest you first experiment with the plugin in a freshly generated *hello world* app.

**Comment by TheLastGimbus** [comment] 2021-03-28 20:46
Yes, that's exactly what I did and listed above:

> I made a separate empty app to debug this

**Comment by christocracy** [comment] 2021-03-29 17:16
Confirmed.  Seems flutter 2 has mucked something up wrt headless initialization.

Please try installing from Git and confirm the problem is solved:

```yaml
dependencies:
  background_fetch:
    git:
      url: https://github.com/transistorsoft/flutter_background_fetch
      ref: release-0.7.2
```

**Comment by TheLastGimbus** [comment] 2021-03-31 14:04
Hmm, nope. Same app, just this dependency changed, `flutter clean`ed and freshly installed, still brakes. Still prints:
```
03-31 16:01:16.470 15901 15973 E flutter : Receiver: null
03-31 16:01:16.470 15901 15973 E flutter : Tried calling: toRawHandle()
03-31 16:01:16.470 15901 15973 E flutter : #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
03-31 16:01:16.470 15901 15973 E flutter : #1      BackgroundFetch.registerHeadlessTask (package:background_fetch/background_fetch.dart:606:51)
03-31 16:01:16.470 15901 15973 E flutter : #2      main (package:dupa12/main.dart:7:19)
03-31 16:01:16.470 15901 15973 E flutter : #3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:140:25)
03-31 16:01:16.470 15901 15973 E flutter : #4      _rootRun (dart:async/zone.dart:1354:13)
03-31 16:01:16.470 15901 15973 E flutter : #5      _CustomZone.run (dart:async/zone.dart:1258:19)
03-31 16:01:16.470 15901 15973 E flutter : #6      _runZoned (dart:async/zone.dart:1788:10)
03-31 16:01:16.470 15901 15973 E flutter : #7      runZonedGuarded (dart:async/zone.dart:1776:12)
03-31 16:01:16.470 15901 15973 E flutter : #8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:133:5)
03-31 16:01:16.470 15901 15973 E flutter : #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
03-31 16:01:16.470 15901 15973 E flutter : #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
When `BackgroundFetch.registerHeadlessTask()` is run, even if I add `WidgetsFlutterBinding.ensureInitialized()` before it

And then headless doesn't work, of course. Tested on Huawei tablet and Pixel phone

**Comment by TheLastGimbus** [comment] 2021-04-01 00:20
# :tada:

Yup, working now! Thanks!

**Comment by TheLastGimbus** [comment] 2021-04-01 00:21
@yamachaso test it yourself and we can go ahead and close this :smile:

**Comment by christocracy** [comment] 2021-04-01 12:52
[`0.7.2` is released.](https://pub.dev/packages/background_fetch)

**Closed by christocracy** 2021-04-01 12:52 UTC
